### ISSUE TITLE
Conda recipe for pynio broken on Mac

### ISSUE THREAD

**Issue by marylhaley** [conda-forge/pynio-feedstock#10]
I'm using conda V4.1.11 on an El Capitan Mac.

I tried to install pynio from conda-forge using the following:

```shell
conda create -n condaforge_test -c conda-forge pynio
source activate condaforge_test
```

but a simple "import" of "Nio" failed:

```shell
python -c 'import Nio'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/haley/miniconda2/envs/condaforge_test/lib/python2.7/site-packages/PyNIO/Nio.py", line 83, in <module>
    from nio import *
ImportError: dlopen(/Users/haley/miniconda2/envs/condaforge_test/lib/python2.7/site-packages/PyNIO/nio.so, 2): Library not loaded: @rpath/libjasper.1.dylib
  Referenced from: /Users/haley/miniconda2/envs/condaforge_test/lib/python2.7/site-packages/PyNIO/nio.so
  Reason: image not found
(condaforge_test) bash-3.2$ 
```

**Comment by ocefpaf** [comment]
I believe that `libjasper` was available via `gdal` but a recent `gdal` update switched from `jasper` to `openjpeg`. For now you can do `conda install jasper -c conda-forge` and (hopefully) it will work.

Thanks for the report! I am specifying `jasper` as a direct dependency of `pynio` and checking if that fixes this.
