### ISSUE TITLE
Failing builds

### ISSUE THREAD

**Issue by WeatherGod** [conda-forge/pynio-feedstock#100]
Seems like the last successful build happened a little over a year ago on April 2nd. Do we know what is wrong? Would be nice to get the builds working for py3.9 and soon py3.10.

**Comment by WeatherGod** [comment]
From the logs, it looks like conda is reporting a huge number of unsatisfiable package specifications, so it can't even get the build environment set up.

**Comment by WeatherGod** [comment]
[conda-fail.txt](https://github.com/conda-forge/pynio-feedstock/files/6417543/conda-fail.txt)

**Comment by fulminemizzega** [comment]
Take a look here https://github.com/akrherz/pynio-feedstock/pull/1
And here https://github.com/NCAR/pynio/issues/44

**Comment by fulminemizzega** [comment]
This can be closed, new builds are available for python 3.7, 3.8, 3.9 and 3.10.
