### ISSUE TITLE
gdal version?

### ISSUE THREAD

**Issue by khallock** [conda-forge/pynio-feedstock#18]
@ocefpaf,

Is there any reason we need to have gdal pinned to version "1.11.*"? This older version of gdal has "proj.4" as a dependency, while PyNIO uses "proj4" (I saw that you just updated the proj4 recipe yourself 10 days ago).

I was able to successfully build PyNIO using this recipe even after changing the gdal dependency to version "2.1.*". The only test that failed was seemingly due to an OPeNDAP server being down for maintenance.

**Comment by ocefpaf** [comment]
> Is there any reason we need to have gdal pinned to version "1.11.*"?

I do not recall. Maybe I just forgot to unpin it here. We can always test with a PR :wink: 

See #19
