### ISSUE TITLE
Error trying to install

### ISSUE THREAD

**Issue by guilhermecgs** [conda-forge/pynio-feedstock#24]
I´m receiving an error trying to install ...

C:\Anaconda2>conda config --add channels conda-forge
Warning: 'conda-forge' already in 'channels' list, moving to the front

C:\Anaconda2>conda install pynio
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: .
Error: Package missing in current win-64 channels:
  - pynio

You can search for packages on anaconda.org with

    anaconda search -t conda pynio

**Comment by ocefpaf** [comment]
Sorry but `pynio` is not available on Windows. If you have experience building software on Windows please send a PR.

**Comment by khallock** [comment]
Hi @guilhermecgs,

For what it's worth, native Windows support is something we intend to have for PyNIO eventually: NCAR/pynio#8

If you are using Windows 10, you could try installing [Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about). This would allow you to run Linux binaries (including PyNIO) in an "Ubuntu-like" environment on Windows.
