### ISSUE TITLE
"dev" label for development snapshot builds

### ISSUE THREAD

**Issue by khallock** [conda-forge/pynio-feedstock#36]
This idea was proposed by @ocefpaf ([NCAR/pynio#10](https://github.com/NCAR/pynio/issues/10#issuecomment-373179560)).

Should we create a new label for "dev" builds of PyNIO that can be installed using "--channel conda-forge/label/dev"?

How difficult would it be to maintain a branch of this repo specifically for the "dev" label, and could we create the "dev" builds using Travis CI and Circle CI the same way the stable builds are currently done?

**Comment by ocefpaf** [comment]
> Should we create a new label for "dev" builds of PyNIO that can be installed using "--channel conda-forge/label/dev"?

I already created the branch :smile: 

https://github.com/conda-forge/pynio-feedstock/tree/dev

> How difficult would it be to maintain a branch of this repo specifically for the "dev" label

It works the same as the master branch for the stable version.

> could we create the "dev" builds using Travis CI and Circle CI the same way the stable builds are currently done?

Anything on a branch will be built and uploaded the same way. We only need to change the `conda-forge.yml` to look [like this](https://github.com/conda-forge/gmt-feedstock/blob/devel/conda-forge.yml#L9) so the builds go the right label.

**Comment by khallock** [comment]
Perfect! I'll add those lines to `conda-forge.yml` and then make the necessary changes to `meta.yaml`.

This is slightly unrelated, but I noticed that there's a new `conda-forge-pinning` package... is there any documentation on how to use this?

**Comment by ocefpaf** [comment]
> This is slightly unrelated, but I noticed that there's a new `conda-forge-pinning` package... is there any documentation on how to use this?

No docs yet but in theory things will be easier b/c, once we move to `conda-build 3`,  we will be able to just remove the pinning from the recipes and let that package handle the pinning at build time.

Right now there is nothing we need to do.

**Comment by khallock** [comment]
> No docs yet but in theory things will be easier b/c, once we move to conda-build 3, we will be able to just remove the pinning from the recipes and let that package handle the pinning at build time.
> 
> Right now there is nothing we need to do.
> 

Sounds great to me, that should hopefully prevent some headaches in the future.

Do you have any recommendations for version numbers and build strings for these "dev" builds? On the `ncar` channel, I used versions like `dev_20170921` (where 2017-09-21 was the commit date) and build strings such as `05806a2_py36` (05806a2 was the commit ID). I suppose that if we're using the "dev" label, explicitly including "dev" in the version string is no longer necessary.

**Comment by ocefpaf** [comment]
> Do you have any recommendations for version numbers and build strings for these "dev" builds? On the `ncar` channel, I used versions like `dev_20170921` (where 2017-09-21 was the commit date) and build strings such as `05806a2_py36` (05806a2 was the commit ID).

Let's use [pep440](https://www.python.org/dev/peps/pep-0440/) and we can use [this trick](https://stackoverflow.com/questions/35522047/pep440-compliant-and-git-describe-info-available-from-deployed-package) to get the hash there.

> I suppose that if we're using the "dev" label, explicitly including "dev" in the version string is no longer necessary.

Even though it is kind of redundant it is nice to have the `dev` in the version string so people can find out what they are using with commands like `conda list`.

**Comment by ocefpaf** [comment]
Done in #38 , to install from dev label you can do:

```shell
$ conda install -c conda-forge/label/dev pynio
```
