### ISSUE TITLE
Error channels

### ISSUE THREAD

**Issue by ycherrq** [conda-forge/pynio-feedstock#64]
Issue:
conda install skimage
PackageNotFoundError: Packages missing in current channels:

  - skimage

We have searched for the packages in the following channels:

  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch
---------------------

**Comment by ocefpaf** [comment]
> conda install skimage

That is unrelated to `pynio`, the name of the package is `scikit-image` not `skimage` (which is the import name), and based on the list of channels there you are not using `conda-forge` at all.

**Comment by ycherrq** [comment]
OK,thank you

**Comment by ycherrq** [comment]
I have the other problem,can you tall me why, and help me

conda create --name pyn_env --channel conda-forge/label/cf201901 pyniopyngl
Fetching package metadata .............

PackageNotFoundError: Packages missing in current channels:

  - pyniopyngl

We have searched for the packages in the following channels:

  - https://conda.anaconda.org/conda-forge/label/cf201901/linux-64
  - https://conda.anaconda.org/conda-forge/label/cf201901/noarch
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch

**Comment by ocefpaf** [comment]
There

**Comment by ycherrq** [comment]
How to solve it?

**Comment by ocefpaf** [comment]
Add a space between between the packages.
BTW these are usage questions and not problens with the packages or conda-forge infrastructure. Please take a look at conda's documentation before opening issues.

**Comment by ycherrq** [comment]
ok,thank you
